server:
  http_listen_port: 3100
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://xxxx:xxxxxxxxxxxxxxxxxx@logs-prod-us-central1.grafana.net/api/prom/push

scrape_configs:
  - job_name: raa_production
    static_configs:
      - targets:
          - localhost
        labels:
          job: projectChangeMe_production
          __path__: /logs/projectChangeMe.log