
def sendEmail(needFundsWalletsOuput, subject){
    println "sending email = emailPath"
    def emailBody = """<!DOCTYPE html>
                        <html>
                        <head>
                            <style type="text/css">
                            body {
                                font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif;
                            }

                            h2 {
                                margin-left: 10px;
                                margin-top: 10px;
                            }

                            .SynthesisName {
                                color: #5e76b5;
                                font-weight: bold;
                            }
                            </style>
                        </head>
                        <body>
                            <p>
                                Hi,
                                
                                Message from Bridge wallets checker. The following wallets are out of funds: 
                                <br>
                                <br>
                                ${needFundsWalletsOuput}
                                <br>
                                <br>
                                <b>
                                WARNING: Please check wallets manually before putting any funds to those wallets.
                                </b>
                                <br>
                                <br>
                                for troubleshoot follow this link (you need to connect to VPN to access it)
                                jenkins build url: ${env.BUILD_URL}console
                                <br>
                                <br>
                            </p>

                        </body>
                        </html>

                    """
    // emailext (from: "notifications@sovryn.app", to:"ororosovryn@protonmail.com, shlumperx@gmail.com, elan@remake.money", mimeType: 'text/html', subject: subject, body: emailBody)
    emailext (from: "notifications@sovryn.app", to:"shlumperx@gmail.com", mimeType: 'text/html', subject: subject, body: emailBody)

}

pipeline {
    agent any
    triggers {
        cron('0 */2 * * *')
    }
    options {
        ansiColor('xterm')
        buildDiscarder(
                logRotator(numToKeepStr: '20')
        )
        timestamps()
    }
    stages {
        stage('check wallets') {
            steps {
                dir("federator-wallets-checker") {
                    script {
                        sh "npm install"
                        def checkerstdout = sh(returnStdout: true, script: "node checker.js").trim()
                        List lines = checkerstdout.split( '\n' ).findAll { it.contains( 'ERROR' ) }
                        if (lines.size() > 0) {
                            needFundsWalletsOuput = lines.join("<br>")
                            println("needFundsWalletsOuput: " + needFundsWalletsOuput)
                            sendEmail(needFundsWalletsOuput, "☠️ Bridge warning!")
                        }
                        else {
                            println("all good nothing to do")
                        }
                    }   
                }
            }
        }
    }
}


