
def sendEmail(needFundsWalletsOuput, subject){
    println "sending email = emailPath"
    def emailBody = """<!DOCTYPE html>
                        <html>
                        <head>
                            <style type="text/css">
                            body {
                                font-family: 'Trebuchet MS', Arial, Helvetica, sans-serif;
                            }

                            h2 {
                                margin-left: 10px;
                                margin-top: 10px;
                            }

                            .SynthesisName {
                                color: #5e76b5;
                                font-weight: bold;
                            }
                            </style>
                        </head>
                        <body>
                            <p>
                                The following are out of funds: 
                                <br>
                                ${needFundsWalletsOuput}
                                for troubleshoot follow this link (you need to connect to VPN to access it)
                                jenkins build url: ${env.BUILD_URL}console
                                <br>
                                <br>
                            </p>

                        </body>
                        </html>

                    """
    emailext (from: "notifications@sovryn.app", to:"shlumperx@gmail.com, elan@remake.money", mimeType: 'text/html', subject: subject, body: emailBody)
}

pipeline {
    agent any
    triggers {
        cron('H */4 * * 1-5')
    }
    options {
        ansiColor('xterm')
        buildDiscarder(
                logRotator(numToKeepStr: '20')
        )
        timestamps()
    }
    stages {
        stage('check wallets') {
            steps {
                dir("federator-wallets-checker") {
                    script {
                        sh "npm install"
                        def checkerstdout = sh(returnStdout: true, script: "node checker.js").trim()
                        List lines = checkerstdout.split( '\n' ).findAll { it.contains( 'ERROR' ) }
                        needFundsWalletsOuput = lines.join("\n")
                        println("needFundsWalletsOuput: " + needFundsWalletsOuput)
                        sendEmail(needFundsWalletsOuput, "☠️ Bridge warning!",){
                    }   
                }
            }
        }
    }
}


