---
- hosts: localhost
  tasks:
    - name: Update apt packages
      become: true
      apt:
        update_cache: yes

    - name: Install some packages
      apt: name={{ item }} state=installed
      with_items:
        - awscli
