{
 "title": "Staging - App Monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [
  "docker",
  "app"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "environment", "query": "project-staging" }
  ]
 },
 "panels": [
  {
   "title": "Total CPU Usage (containers)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\", origin_prometheus=\"project-staging\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", origin_prometheus=\"project-staging\"}) / sum(node_memory_MemTotal_bytes{origin_prometheus=\"project-staging\"}) * 100"
    }
   ]
  },
  {
   "title": "Used Disk %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\", origin_prometheus=\"project-staging\"} / node_filesystem_size_bytes{mountpoint=\"/\", origin_prometheus=\"project-staging\"}) * 100"
    }
   ]
  },
  { "title": "App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Logback",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(logback_events_total{origin_prometheus=\"project-staging\", level=\"error\"}[10m])",
     "legendFormat": "Errors Rate"
    },
    {
     "expr": "sum(rate(logback_events_total{origin_prometheus=\"project-staging\"}[10m]))",
     "legendFormat": "Total Logs Rate"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{origin_prometheus=\"project-staging\",}[5m])",
     "legendFormat": "Request count"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{origin_prometheus=\"project-staging\"}[5m]) / rate(http_server_requests_seconds_count{origin_prometheus=\"project-staging\"}[5m]) ",
     "legendFormat": "Mean response time"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\", origin_prometheus=\"project-staging\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\", origin_prometheus=\"project-staging\"}[5m]) * 100)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\", origin_prometheus=\"project-staging\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\", origin_prometheus=\"project-staging\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\", origin_prometheus=\"project-staging\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}