{
 "title": "Docker monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "environment", "query": "project-uat" }
  ]
 },
 "panels": [
  {
   "title": "Total CPU Usage (containers)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\", origin_prometheus=\"project-uat\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\", origin_prometheus=\"project-uat\"}) / sum(node_memory_MemTotal_bytes{origin_prometheus=\"project-uat\"}) * 100"
    }
   ]
  },
  {
   "title": "Used Disk %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{mountpoint=\"/\", origin_prometheus=\"project-uat\"} / node_filesystem_size_bytes{mountpoint=\"/\", origin_prometheus=\"project-uat\"}) * 100"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(meteor_errors{origin_prometheus=\"project-uat\"}[10m])"
    },
    {
     "expr": "meteor_errors{origin_prometheus=\"project-uat\"}"
    }
   ]
  },
  {
   "title": "Connected Users",
   "type": "stat",
   "description": "Amount of connected sockets",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "meteor_metrics{method=\"sockets.count\", origin_prometheus=\"project-uat\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\", origin_prometheus=\"$environment\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\", origin_prometheus=\"project-uat\"}[5m]) * 100)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\", origin_prometheus=\"project-uat\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\", origin_prometheus=\"project-uat\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\", origin_prometheus=\"project-uat\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}