version: "3"
services:

  prometheus:
    image: prom/prometheus:v2.18.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ../development/configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: always
    network_mode: host
    depends_on:
      - cadvisor
      - node-exporter

  cadvisor:
    image: gcr.io/google-containers/cadvisor@sha256:46d4d730ef886aaece9e0a65a912564cab0303cf88718d82b3df84d3add6885c
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    restart: always
    ports:
      - 9000:8080

  node-exporter:
    image: prom/node-exporter:v1.0.0-rc.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
    restart: always
    ports:
      - 9100:9100