version: "3"
services:

  prometheus:
    image: prom/prometheus:v2.18.1
    ports:
      - 127.0.0.1:9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - /configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: always
    depends_on:
      - cadvisor
      - promtail
      - node-exporter

  cadvisor:
    image: gcr.io/google-containers/cadvisor@sha256:46d4d730ef886aaece9e0a65a912564cab0303cf88718d82b3df84d3add6885c
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    ports:
      - 127.0.0.1:9000:8080
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.0.0-rc.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
    restart: always
    ports:
      - 9100:9100

  promtail:
    image: grafana/promtail:1.4.1
    volumes:
      - "/configs/promtail-config.yml:/config/config.yml:ro"
      - "/var/log/projectChangeMe:/logs:ro"
    command:
      - --config.file=/config/config.yml
      - --log.level=debug
    ports:
      - 127.0.0.1:3100:3100
    restart: always